version: '2'
services:

  vault:
    image: vault:latest
    container_name: vault_server
    command: server
    volumes:
        - ./policies:/vault/policies:rw
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "listener": {"tcp": {"address":"0.0.0.0:8200","tls_disable":"1"}} }'
